### ISSUE TITLE
README instructions not working

### ISSUE THREAD

**Issue by WebFreak001** [skoppe/spasm#1]
```
spasm 0.0.6: building configuration "library"...
ldc2: Unknown command line argument '-link-internally'.  Try: 'ldc2 -help'
ldc2: Did you mean '-print-after-all'?
ldc2 failed with exit code 1.
```

ldc version:
```
LDC - the LLVM D compiler (1.12.0):
  based on DMD v2.082.1 and LLVM 7.0.0
  built with LDC - the LLVM D compiler (1.11.0)
  Default target: x86_64-pc-linux-gnu
  Host CPU: penryn
  http://dlang.org - http://wiki.dlang.org/LDC
```

I ran:
```
dub init
<add spasm 0.0.6 dependency>
dub upgrade
dub run spasm:bootstrap-webpack
npm install
npx webpack
<insert example/todo-mvc/source/app.d into project>
dub build --compiler=ldc2 --build=release
```

**Comment by skoppe** [comment]
Thanks for trying it out and reporting an issue.

I had the exact same issue. On https://wiki.dlang.org/Generating_WebAssembly_with_LDC it says to use LDC's official prebuilt release package. Eventually I just ran the dlang's install.sh script in a fresh ubuntu docker container, that worked.

It could be that with ldc 1.12 `-link-internally` is no longer necessary. I will check and adjust if necessary.

**Comment by skoppe** [comment]
Indeed, LDC 1.12 no longer requires `-link-internally`. I have removed it and pushed 0.0.7. It will take a few minutes before code.dlang.org picks it up.

**Comment by WebFreak001** [comment]
I removed link-internally but now it's saying my LDC doesn't support the wasm target

**Comment by skoppe** [comment]
Also had that issue. It seems your installation of LDC doesn't have the wasm target. You can validate that by running `ldc2 --version`, the `wasm32` target needs to be present.

I solved it by installing ldc in a fresh container with the dlang's install.sh script.

**Comment by skoppe** [comment]
You can have a look at the added wercker.yml file to see how I build the project on the CI.

**Comment by skoppe** [comment]
Side note: As of spasm 0.0.8, ldc 1.13.0-beta2 is the minimum supported version.

you can use the `dlang2/ldc-ubuntu` docker image.
