### ISSUE TITLE
latest changes broke todo-mvc example functionality

### ISSUE THREAD

**Issue by skoppe** [skoppe/spasm#17]
specifically the complete checkbox and the associated styles

**Comment by skoppe** [comment]
somewhere between 0.1.8 and 0.1.9

**Comment by Beyarz** [comment]
I think it was 0.1.8. Not sure though.

**Comment by skoppe** [comment]
commit 756cb07cd1f0cfb7be6c264bd17571d544caafe3 `Add a way to override styles and to override component fields` caused troubles

**Comment by skoppe** [comment]
it was a pain to bisect because since v0.1.0 and now I moved from ldc 1.12-beta to 1.15-beta, which had a) breaking changes with exports and b) refactored `_d_array_cast_len` to `_d_arraycast_len`, on top of the changes in spasm itself and some minor refactoring in the todo-mvc example.

I **really** need to use https://github.com/cypress-io/cypress-example-todomvc in the pipeline to prevent this.

**Comment by skoppe** [comment]
Fixed in 9d198eec87c8099d739c5378ce6369e22ab4c403
