### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Duckxz** [skoppe/spasm#27]
`Performing "debug" build using /usr/bin/ldc2 for x86_64.
spasm 0.1.13+commit.34.g7fe557b: building configuration "library"...
Warning: Assuming critical section size = 40 bytes
/usr/bin/ldc2 failed with exit code 1.`

**Comment by s0kil** [comment]
@Duckxz I have had the same issue, fixed by using `bin/ldc2` binary from [ldc](https://github.com/ldc-developers/ldc/releases)

**Comment by skoppe** [comment]
I have never used a debug build. Don't know if it even works.

**Comment by skoppe** [comment]
I am upgrading to ldc 1.16.0 and am seeing the same issue. Investigating...

**Comment by skoppe** [comment]
The `Warning: Assuming critical section size = 40 bytes` even happens with the simple example at https://wiki.dlang.org/Generating_WebAssembly_with_LDC.

I am using the `dlang2/ldc-ubuntu:1.16.0` docker image.

**Comment by skoppe** [comment]
Caused by https://github.com/ldc-developers/ldc/issues/3118

workaround is to put buildRequirements allowWarnings in your dub.sdl/json
