### ISSUE TITLE
Why building my project will try to link in all spasm symbols?

### ISSUE THREAD

**Issue by dukc** [skoppe/spasm#29]
If I `dub build` the DOM example, the WASM binary will require only those sumbols from JS export table it uses. However, doing the same for my own project, with exactly the same DUB arguments in both invocation and `dub.sdl`, results in a binary that demands everything, or at least a huge amount of stuff from spasm to be linked in. Even stranger, this happens only at Linux (OpenSUSE Tumbleweed), not at Windows. Ldc version is 1.15.0 (at both systems) and dub version is 1.14.0.

I'm investigating this myself, but I decided to open a report just in case somebody else has already figured this out.

**Comment by skoppe** [comment]
Can you do a `dub build --build=release -v` and show the ldc invocation? As well as the linker.

**Comment by dukc** [comment]
> Can you do a `dub build --build=release -v` and show the ldc invocation? As well as the linker.

dom:
```
/home/yleinen/bin/ldc2 -mtriple=wasm32-unknown-unknown-wasm -Oz -fvisibility=hidden -mtriple=wasm32-unknown-unknown-wasm -of.dub/build/application-release-linux.posix-x86_64-ldc_2085-E01D34567FCF8244127B26700F2B046B/dom -release -enable-inlining -Hkeep-all-bodies -O3 -w -betterC -oq -od=.dub/obj -d-version=Have_dom -d-version=Have_spasm -d-version=Have_optional -d-version=Have_stdx_allocator -d-version=Have_silly -d-version=Have_bolts -Isource/ -I../../source/ -I../../../../optional-0.10.0/optional/source/ -I../../../../optional-0.10.0/optional/tests -I../../../../silly-0.8.0/silly -I../../../../bolts-0.11.1/bolts/source/ -I../../../../stdx-allocator-2.77.3/stdx-allocator/source/ source/app.d ../../.dub/build/library-release-linux.posix-x86_64-ldc_2085-17928F65
4C15233377E025DD985D6CE3/libspasm.a ../../../../optional-0.10.0/optional/.dub/build/unittest-release-linux.posix-x86_64-ldc_2085-D4D9CB62C5E0690796CB6CD1862320DC/liboptional.a ../../../../bolts-0.11.1/bolts/.dub/build/library-release-linux.posix-x86_64-ldc_2085-BAE4F12006B00A793BEA8153D0E3FE10/libbolts.a ../../../../stdx-allocator-2.77.3/stdx-allocator/.dub/build/library-release-linux.posix-x86_64-ldc_2085-9450FA57A0580D60AFE2D68A133A40BD/libstdx-allocator.a -L=-strip-all -L=-allow-undefined -L=-import-memory -L=--export-table -L=--export=domEvent -L=--export=allocString -vcolumns
```

dmodule (my project):
```
/home/yleinen/bin/ldc2 -mtriple=wasm32-unknown-unknown-wasm -Oz -fvisibility=hidden -mtriple=wasm32-unknown-unknown-wasm -of.dub/build/stoneworks-release-linux.posix-x86_64-ldc_2085-7F3D0D36E4C26F6EAB107C0F9C443A11/dmodule -release -enable-inlining -Hkeep-all-bodies -O3 -w -betterC -oq -od=.dub/obj -d-version=StoneworksEdition -d-version=Have_dmodule -d-version=Have_spasm -d-version=Have_optional -d-version=Have_stdx_allocator -d-version=Have_silly -d-version=Have_bolts -Isource/ -I../../../.dub/packages/spasm-0.1.13/spasm/source/ -I../../../.dub/packages/optional-0.10.1/optional/source/ -I../../../.dub/packages/optional-0.10.1/optional/tests -I../../../.dub/packages/silly-0.8.2/silly -I../../../.dub/packages/bolts-0.11.1/bolts/source/ -I../../../.dub/packages/stdx-allocator-2.77.3/stdx-allocator/source/ source/app.d source/dmodule.d source/memoryutil.d source/phobosadapt.d ../../../.dub/packages/spasm-0.1.13/spasm/.dub/build/library-release-linux.posix-x86_64-ldc_2085-D90B5F755B84599D453EC6F3EE27812F/libspasm.a ../../../.dub/packages/optional-0.10.1/optional/.dub/build/unittest-release-linux.posix-x86_64-ldc_2085-2E0ECD47D85E0021CB4B2383E638D8C1/liboptional.a ../../../.dub/packages/bolts-0.11.1/bolts/.dub/build/library-release-linux.posix-x86_64-ldc_2085-30B88D3FD16A9E5595BCB60B67C0F774/libbolts.a ../../../.dub/packages/stdx-allocator-2.77.3/stdx-allocator/.dub/build/library-release-linux.posix-x86_64-ldc_2085-9D020CDD4CAE3AE2C6C5289CFCE7F91D/libstdx-allocator.a -L=-strip-all -L=--export-dynamic -L=-allow-undefined -L=-import-memory -L=--export-table -L=--export=domEvent -L=--export=allocString -vcolumns
```

My default linker is gold, but ldc config file orders `-link-internally` on wasm compilations so presumably the linker is LLD for these compilations.

Oh, and I forgot to mention: Even my project will link correctly, if I only use spasm handles and string conversions. This bug kicks in when I try to call any function that handles HTML elements.

**Comment by dukc** [comment]
For me, the most likely explanation seems that there is some sort of time/amount cutoff for the symbol stripper s.t. if the program is large enough, symbol stripping stops working. That would also explain why the stripper works on Windows: as Windows requires commenting needless parts of `stdx.allocator` out manually, the amount of symbols decreases.

But I don't know the compiler switch to adjust that cutoff, if there is one.

**Comment by skoppe** [comment]
Your project sets the `--export-dynamic` linker flag, if I do that on the dom example I also get lots of exported symbols.

Ldc indeed uses the wasm-ld, as the others don't understand wasm.

> This bug kicks in when I try to call any function that handles HTML elements.

You mean any of the functions from `spasm.bindings`?

**Comment by dukc** [comment]
> Your project sets the `--export-dynamic` linker flag, if I do that on the dom example I also get lots of exported symbols.

Yes, removing that fixed it. I thought I had already tested that and it wouldn't work. Likely explanation: forgot to save `dub.sdl` the last time before rebuilding. Thank you.

> 
> > This bug kicks in when I try to call any function that handles HTML elements.
> 
> You mean any of the functions from `spasm.bindings`?

Yes
