### ISSUE TITLE
Pass spasm struct as child

### ISSUE THREAD

**Issue by henriklundgren** [skoppe/spasm#39]
Hi,

Apologize before-hand if I picked the wrong forum to ask my question.

How would you pass a Spasm struct instead of a `HTMLElement`?

```d
struct X
{
  mixin Node!Y;
}
```

Or what is the recipe to accomplish similar?

**Comment by skoppe** [comment]
Hi,

There is no dedicated forum for this. Here is as good a place as any.

You can do the following:

```D
struct X
{
    mixin Node!"div"; // optional
    @child Y y1;
    @child Y y2; // can have multiple children
}
```

A good example of recipes would be the [todo-mvc example](https://github.com/skoppe/spasm/blob/master/examples/todo-mvc/source/app.d)
