### ISSUE TITLE
`Document.createElement` passes string of '\0' chars only to JS in `v0.2.0-beta.6`

### ISSUE THREAD

**Issue by denis-sh** [skoppe/spasm#43]
Testcase:
```
dub init -f sdl -n test-spasm spasm
cd test-spasm
sed -i 's/~>0.1.13/>=0.1.13/' dub.sdl
echo 'dflags "-betterC"' >> dub.sdl
dub upgrade --prerelease
dub run spasm:bootstrap-webpack
wget -O source/app.d https://raw.githubusercontent.com/skoppe/spasm/master/examples/dom/source/app.d
sed -i '/@safe/d' source/app.d
dub build --build=release --build-mode=allAtOnce
dub run spasm:webidl -- --bindgen
npm install
npm run start
```

Output:
```
Failed to execute 'createElement' on 'Document': The tag name provided ('\0\0\0') is not a valid name.
```
Here `'\0\0\0\'` is actually a string of 3 symbols each with code zero. So the length is passed correctly (from expected `"div"`) but data contains zeros only.

This problem is present in `v0.2.0-beta.6`, but in `v0.1.13` the string is passed correctly.

**Comment by skoppe** [comment]
Can you inspect the output of the 2 dub run commands? I suspect at least one is running version 0.1.13 and the generated js glue code isn't compatible with 0.2.0

dub should say something like:

```
Running /root/.dub/packages/spasm-0.2.0-beta.6/spasm/bootstrap-webpack/spasm_bootstrap-webpack
```

and 

```
Running /root/.dub/packages/spasm-0.2.0-beta.6/spasm/webidl/spasm_webidl --bindgen
```

See for backstory
https://github.com/dlang/dub/issues/1751
https://github.com/dlang/dub/issues/1040

**Comment by denis-sh** [comment]
Yes, looks like this was the case. I just removed `~/.dub/packages` and now, as I have only one version of `spasm` installed, everything works fine. Thank you.

Maybe it's possible to add some version check for bindings so at least error message is better? Like `WASM binary uses spasm version x.x.x but bindings are generated for x.x.x`. At least it may help in future.

**Comment by skoppe** [comment]
Glad to hear you found it.

Yeah, I could do that for future versions, good idea.
