### ISSUE TITLE
Can we please get a hello world canvas OR WebGL example?

### ISSUE THREAD

**Issue by Zireael07** [skoppe/spasm#44]
Underrun is awesome, but overkill for what I'm thinking of (just a triangle or a "Hello world" text in WebGL).

**Comment by skoppe** [comment]
Sure. Here is an [canvas one](https://github.com/skoppe/spasm/tree/master/examples/canvas), plus [demo](https://skoppe.github.io/spasm/examples/canvas/index.html). For WebGL it is similar, but I refer to the canvas api docs for [getContext()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext)
