### ISSUE TITLE
broken style in todo mvc demo

### ISSUE THREAD

**Issue by WebFreak001** [skoppe/spasm#47]
Currently the todo demo looks like this:
![image](https://wfr.moe/f6bCG4.png)

https://skoppe.github.io/spasm/examples/todo-mvc/

(in Firefox)

**Comment by skoppe** [comment]
Yeah, it lazy-loads the css, but sometimes that doesn't quite work or you see a flash of unstyled content, will change.

**Comment by WebFreak001** [comment]
in Firefox it's constantly like this
