### ISSUE TITLE
How does this attr work?

### ISSUE THREAD

**Issue by WebFreak001** [skoppe/spasm#48]
I'm currently going through the code and unittests, documenting along the way but I don't get how this works yet:
```d
struct Inner {
  mixin Node!"span";
  @attr int* key;
}
struct App {
  mixin Node!"div";
  int key = 0;
  @child Inner inner;
}
App app;
auto node = app.renderToNode;
node.renderToString().should == `<div><span key=0></span></div>`;
app.update.key = 5;
node.renderToString().should == `<div><span key=5></span></div>`;
```

why does the app.key affect the app.inner.key? Shouldn't the inner key because it is a pointer not have any effect before being set to non-null?

Especially because the `@attr` code looks almost identical to the `@prop` code in the implementation I wouldn't assume that this would happen.

**Comment by skoppe** [comment]
Yeah, that is the whole trick, it does get set to a value, in the first render to the address of `app.key`.

It is a bit magical. The idea was that updates to one value would propagate freely without any copies.

Don't spend too much time on it. After I finally finish porting druntime to wasm I am going to revamp spasm and create a dsl syntax much like below, which is a snippet from production code:

```D
 void render(Renderer)(Renderer node) @safe {
    import std.range : iota, enumerate, chain;
    import std.conv : to;
    auto rows = iota(data.length).enumerate();
    auto columns = table.columns.enumerate();
    mixin(toHtml!q{
        "table" {
          class = table.styles.dedupeStyles;
          "thead" {
            class = table.headStyles.dedupeStyles;
            auto headers = table.headers;
            headers { header =>
                "tr" {
                auto cells = header.data.cells;
                cells { cell =>
                    auto content = cell.data.getContent(table, data);
                  "td" {
                    colspan = cell.data.span.to!string;
                    class = chain(table.headerStyles, header.data.styles, cell.data.styles).dedupeStyles;
                    @textContent = content;
                  }
                }
              }
            }
            "tr" {
              columns { column =>
                  "td" {
                  class = chain(table.headerStyles, column.value.data.styles).dedupeStyles;
                  @textContent = column.value.data.title;
                }
              }
            }
          }
          "tbody" {
            rows { row =>
                "tr" {
                columns { col =>
                  auto styledData = col.value.data.format(table, data[row.index], data, row.index, col.index);
                  "td" {
                    class = chain(table.cellStyles, col.value.data.cellStyles, col.value.data.styles, styledData.styles).dedupeStyles;
                    @textContent = (() @trusted => (cast()(styledData.content)).rawString)();
                  }
                }
              }
            }
          }
        }
      });
  }

```

**Comment by WebFreak001** [comment]
but why does it actually use the app.key value at all? Is that some magic that is defined elsewhere than in the `@attr` code?

**Comment by skoppe** [comment]
Yes, all pointers of @child elements get resolved to their parents. 

I believe it was in https://github.com/skoppe/spasm/blob/master/source/spasm/dom.d#L370

**Comment by skoppe** [comment]
Well, [setPointers](https://github.com/skoppe/spasm/blob/master/source/spasm/dom.d#L451) is where it originates.

**Comment by WebFreak001** [comment]
does it make sense that there is code which handles pointers in attr/prop then? https://github.com/skoppe/spasm/blob/master/source/spasm/dom.d#L982

**Comment by skoppe** [comment]
Yes, that is where the pointer is dereferenced, versus having a normal `@attr int key;`
