### ISSUE TITLE
underrun/spasm/modules/spasm.js vs other spasm.js

### ISSUE THREAD

**Issue by WolfieWerewolf** [skoppe/spasm#5]
I'm just going through the examples and noticed that all of the examples other than underrun.../spasm.js are the same (and come from the bootstrap-webpack).  This one seems to be hand coded... I assume this is test case for additional boilerplate that you will back-port to the bootstrap project eventually?

Thanks
/W

**Comment by skoppe** [comment]
As of v0.1.7 all spasm.js are the same except for todo-mvc. That one I still need to upgrade to the latest.

**Comment by WolfieWerewolf** [comment]
Nice.... more than wanting parity I was curious about the reason.  Was my assumption correct?

**Comment by skoppe** [comment]
Nay, the underrun example was written before the bindings were (dom and fetch examples were written after). The bindings required additional js glue code, so the underrun example didn't have it.
